name: 'publish-spec-to-team'
description: 'Publish a fig spec to fig-teams'
inputs:
  token:
    description: 'A fig access token'
    required: true
  name:
    description: 'The name of the spec'
  team:
    description: 'The target team of the spec'
  spec-path:
    description: 'The path to a spec in the current repository'
  binary-path:
    description: 'The path of the binary to run to generate the spec'
  subcommand-name:
    description: 'The subcommand of the binary used to generate the spec'
  framework:
    description: 'Framework used to build the CLI'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
    - run: |
        OPTIONS=""
        OPTIONS+="${NAME:+ --name $NAME}"
        OPTIONS+="${TEAM:+ --team $TEAM}"
        OPTIONS+="${SPEC_PATH:+ --spec-path $SPEC_PATH}"
        OPTIONS+="${BINARY_PATH:+ --binary-path $BINARY_PATH}"
        OPTIONS+="${SUBCOMMAND_NAME:+ --subcommand-name $SUBCOMMAND_NAME}"
        OPTIONS+="${FRAMEWORK:+ --framework $FRAMEWORK}"
        echo "Running with options: $OPTIONS"
        npx @fig/publish-spec-to-team@1 $OPTIONS
      env:
        FIG_API_TOKEN: ${{ inputs.token }} # This env variable id the one used by the npx command
        NAME: ${{ inputs.name }}
        TEAM: ${{ inputs.team }}
        SPEC_PATH: ${{ inputs.spec-path }}
        BINARY_PATH: ${{ inputs.binary-path }}
        SUBCOMMAND_NAME: ${{ inputs.subcommand-name }}
        FRAMEWORK: ${{ inputs.framework }}
      shell: bash