name: 'Test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:
  repository_dispatch:
    # Use this hook to run tests for updates to the backend or to the @fig/push-spec-to-team CLI
    types: ["dependency-update"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish spec to team
        id: test-1
        uses: ./
        with:
          token: ${{ secrets.FIG_API_TESTING_TOKEN }}
          team: fig-test-pub-spec-gh
          spec-path: ./test-data/test.ts
          framework: cobra
        continue-on-error: true
      - name: Check if previous step failed
        if: steps.test.outcome != 'success'
        run: exit 1
 
  test-minimal-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish spec to team
        id: test-2
        uses: ./
        with:
          token: ${{ secrets.FIG_API_TESTING_TOKEN }}
          team: fig-test-pub-spec-gh
          name: test-2
          spec-path: ./test-data/test.ts
        continue-on-error: true
      - name: Check if previous step failed
        if: steps.test.outcome != 'success'
        run: exit 1  

  test-failing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish spec to team
        id: test-3
        uses: ./
        with:
          token: ${{ secrets.FIG_API_TESTING_TOKEN }}
          team: fig-test-pub-spec-gh
          spec-path: ./test-data/test-failing.ts
        continue-on-error: true
      - name: Check if previous step succeeded
        if: steps.test.outcome == 'success'
        run: exit 1  

  test-missing-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish spec to team
        id: test-4
        uses: ./
        with:
          token: ''
          team: fig-test-pub-spec-gh
          spec-path: ./test-data/test.ts
        continue-on-error: true
      - name: Check if previous step succeeded
        if: steps.test.outcome == 'success'
        run: exit 1  
